services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Guycollegmbh\ApartmentsBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Resources}'

    # Frontend Module Controllers
    Guycollegmbh\ApartmentsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']