services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Guycollegmbh\ApartmentsBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Resources}'